let productos = [
  {
    'nombre': 'Lámpara Dinosaurio LED Multicolor Lightosaurus InnovaGoods',
    'imagen': 'https://www.bigbuy.net/391784-home/lampara-dinosaurio-led-multicolor-lightosaurus-innovagoods.jpg',
    'pvd': '\n                            2,31 €                        ',
    'pvr': '\n                            5,70 €                        ',
  },
  {
    'nombre': 'Cuchillo para Chuletas Quttin Abs (11 Cm)',
    'imagen': 'https://www.bigbuy.net/394004-home/cuchillo-para-chuletas-quttin-abs-11-cm_117947.jpg',
    'pvd': '\n                            0,61 €                        ',
    'pvr': '\n                            0,93 €                        ',
  },
  {
    'nombre': 'Sujetagafas Magnético InnovaGoods (Pack de 2)',
    'imagen': 'https://www.bigbuy.net/326170-home/sujetagafas-magnetico-innovagoods-pack-de-2.jpg',
    'pvd': '\n                            3,78 €                        ',
    'pvr': '\n                            7,53 €                        ',
  },
  {
    'nombre': 'Organizador para Cubiertos Privilege Plástico Transparente (37,5 x 29 x 5 cm)',
    'imagen': 'https://www.bigbuy.net/394177-home/organizador-para-cubiertos-privilege-plastico-transparente-37-5-x-29-x-5-cm_118018.jpg',
    'pvd': '\n                            1,14 €                        ',
    'pvr': '\n                            1,73 €                        ',
  },
  {
    'nombre': 'Cargador Inalámbrico de Madera de Carga Rápida Maple InnovaGoods',
    'imagen': 'https://www.bigbuy.net/341016-home/cargador-inalambrico-de-madera-de-carga-rapida-maple-innovagoods.jpg',
    'pvd': '\n                            8,48 €                        ',
    'pvr': '\n                            15,63 €                        ',
  },
  {
    'nombre': 'Adaptador Bluetooth de Audio',
    'imagen': 'https://www.bigbuy.net/319390-home/adaptador-bluetooth-de-audio.jpg',
    'pvd': '\n                            4,99 €                        ',
    'pvr': '\n                            12,40 €                        ',
  },
  {
    'nombre': 'Palo Selfie Bluetooth',
    'imagen': 'https://www.bigbuy.net/301759-home/palo-selfie-bluetooth.jpg',
    'pvd': '\n                            1,99 €                        ',
    'pvr': '\n                            8,18 €                        ',
  },
  {
    'nombre': 'Dispensador de Agua Automático Recargable InnovaGoods',
    'imagen': 'https://www.bigbuy.net/371588-home/dispensador-de-agua-automatico-recargable-innovagoods.jpg',
    'pvd': '\n                            6,31 €                        ',
    'pvr': '\n                            12,31 €                        ',
  },
  {
    'nombre': 'Reloj Unisex XTRESS XAA1032-41 (40 mm)',
    'imagen': 'https://www.bigbuy.net/394280-home/reloj-unisex-xtress-xaa1032-41-40-mm_118077.jpg',
    'pvd': '\n                            5,49 €                        ',
    'pvr': '\n                            6,70 €                        ',
  },
  {
    'nombre': 'Teclado Gaming CoolBox COO-DGTEM02 Negro',
    'imagen': 'https://www.bigbuy.net/394541-home/teclado-gaming-coolbox-coo-dgtem02-negro_118172.jpg',
    'pvd': '\n                            37,28 €                        ',
    'pvr': '\n                            40,09 €                        ',
  },
  {
    'nombre': 'Grill de Contacto Princess 112415 2000W Negro Acero inoxidable',
    'imagen': 'https://www.bigbuy.net/394338-home/grill-de-contacto-princess-112415-2000w-negro-acero-inoxidable_118137.jpg',
    'pvd': '\n                            26,54 €                        ',
    'pvr': '\n                            28,85 €                        ',
  },
  {
    'nombre': 'Set de Utensilios para Cocina Privilege Bambú (4 Pcs)',
    'imagen': 'https://www.bigbuy.net/394178-home/set-de-utensilios-para-cocina-privilege-bambu-4-pcs_118019.jpg',
    'pvd': '\n                            1,64 €                        ',
    'pvr': '\n                            2,31 €                        ',
  },
  {
    'nombre': 'Cubo para la Basura Tontarelli 45 L Plástico Rectangular (40 X 29 x 65 cm)',
    'imagen': 'https://www.bigbuy.net/393788-home/cubo-para-la-basura-tontarelli-45-l-plastico-rectangular-40-x-29-x-65-cm_117866.jpg',
    'pvd': '\n                            12,31 €                        ',
    'pvr': '\n                            18,69 €                        ',
  },
  {
    'nombre': 'Afeitadora Eléctrica Aprilla AHC-5018 USB Negro',
    'imagen': 'https://www.bigbuy.net/394075-home/afeitadora-electrica-aprilla-ahc-5018-usb-negro_117986.jpg',
    'pvd': '\n                            13,27 €                        ',
    'pvr': '\n                            20,13 €                        ',
  },
  {
    'nombre': 'Tenedor para Carne Quttin (20 cm)',
    'imagen': 'https://www.bigbuy.net/394010-home/tenedor-para-carne-quttin-20-cm_117950.jpg',
    'pvd': '\n                            1,59 €                        ',
    'pvr': '\n                            2,40 €                        ',
  },
  {
    'nombre': 'Auriculares Inalámbricos Magnéticos Deportivos InnovaGoods',
    'imagen': 'https://www.bigbuy.net/375042-home/auriculares-inalambricos-magneticos-deportivos-innovagoods.jpg',
    'pvd': '\n                            9,97 €                        ',
    'pvr': '\n                            18,52 €                        ',
  },
  {
    'nombre': 'Mochila Antirrobo Cruzada InnovaGoods',
    'imagen': 'https://www.bigbuy.net/370994-home/mochila-antirrobo-cruzada-innovagoods.jpg',
    'pvd': '\n                            7,39 €                        ',
    'pvr': '\n                            16,45 €                        ',
  },
  {
    'nombre': 'Mesa de Comedor (180 x 90 x 40 cm) Madera de mindi',
    'imagen': 'https://www.bigbuy.net/393855-home/mesa-de-comedor-180-x-90-x-40-cm-madera-de-mindi_117882.jpg',
    'pvd': '\n                            382,72 €                        ',
    'pvr': '\n                            420,99 €                        ',
  },
  {
    'nombre': 'Set de Utensilios para Cocina Privilege Bambú (5 Pcs)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            2,40 €                        ',
    'pvr': '\n                            3,38 €                        ',
  },
  {
    'nombre': 'Pelador Zig-Zag Quttin (18,5 x 1,5 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            0,71 €                        ',
    'pvr': '\n                            1,08 €                        ',
  },
  {
    'nombre': 'Memoria RAM Kingston HX432C16FB3A/8 8 GB DDR4 PC4-25600',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            41,33 €                        ',
    'pvr': '\n                            43,51 €                        ',
  },
  {
    'nombre': 'Emisor Térmico Digital Taurus CHTA-2000 2000W Blanco',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            81,74 €                        ',
    'pvr': '\n                            86,96 €                        ',
  },
  {
    'nombre': 'Cubo para la Basura Big Hoop Tontarelli 45 L Plástico (ø 39 x 72 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            8,74 €                        ',
    'pvr': '\n                            13,26 €                        ',
  },
  {
    'nombre': 'Soporte Gravitatorio de Móviles para Coche InnovaGoods',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            2,49 €                        ',
    'pvr': '\n                            7,36 €                        ',
  },
  {
    'nombre': 'Salero con Tapa Quttin (14 x 9 x 9,5 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            4,27 €                        ',
    'pvr': '\n                            6,02 €                        ',
  },
  {
    'nombre': 'Fiambrera Bormioli Rectangular (20,3 x 12,3 x 8 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            3,57 €                        ',
    'pvr': '\n                            5,03 €                        ',
  },
  {
    'nombre': 'Kit de Entrenamiento para Fitness BTK',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            8,06 €                        ',
    'pvr': '\n                            20,16 €                        ',
  },
  {
    'nombre': 'Infusor de Té de Silicona Diver·T InnovaGoods',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            2,85 €                        ',
    'pvr': '\n                            6,53 €                        ',
  },
  {
    'nombre': 'Pelador de Fruta y Verdura Privilege (3 uds)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            1,51 €                        ',
    'pvr': '\n                            2,30 €                        ',
  },
  {
    'nombre': 'Reloj Mujer Radiant RA384204 (32 mm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            18,82 €                        ',
    'pvr': '\n                            20,91 €                        ',
  },
  {
    'nombre': 'Fiambrera Cuadrada con Tapa Bormioli (18 x 19 x 8 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            4,06 €                        ',
    'pvr': '\n                            5,72 €                        ',
  },
  {
    'nombre': 'Regadera Resistente',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            2,63 €                        ',
    'pvr': '\n                            3,98 €                        ',
  },
  {
    'nombre': 'Set de Rodillos de Pintura Recargables Antigoteo Roll\'n\'Paint InnovaGoods 5 Piezas',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            6,46 €                        ',
    'pvr': '\n                            16,45 €                        ',
  },
  {
    'nombre': 'Cuchillo Quttin (11 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            0,57 €                        ',
    'pvr': '\n                            0,86 €                        ',
  },
  {
    'nombre': 'Secador de Pelo Aprilla AHD-2131 1600W Negro',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            12,09 €                        ',
    'pvr': '\n                            18,34 €                        ',
  },
  {
    'nombre': 'Cojín Roraima Azul',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            9,82 €                        ',
    'pvr': '\n                            10,80 €                        ',
  },
  {
    'nombre': 'Cubitera Iceland',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            4,43 €                        ',
    'pvr': '\n                            6,25 €                        ',
  },
  {
    'nombre': 'Parches Antimanchas de Sudor para Axilas InnovaGoods (Pack de 10)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            1,98 €                        ',
    'pvr': '\n                            4,95 €                        ',
  },
  {
    'nombre': 'Plancha de Pelo de Cerámica Aprilla AHS-2015 45W Blanco',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            5,97 €                        ',
    'pvr': '\n                            9,05 €                        ',
  },
  {
    'nombre': 'Pesas Lastre con Mangos Walk & Weight (pack de 2)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            3,53 €                        ',
    'pvr': '\n                            8,93 €                        ',
  },
  {
    'nombre': 'Caja Registradora de Madera con Accesorios Kashy InnovaGoods',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            9,69 €                        ',
    'pvr': '\n                            20,58 €                        ',
  },
  {
    'nombre': 'Bandeja para Sofá con Organizador de Mandos InnovaGoods',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            2,99 €                        ',
    'pvr': '\n                            8,18 €                        ',
  },
  {
    'nombre': 'Cortapelos Inalámbrico Aprilla AHC-5030 2 mm Impermeable',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            15,38 €                        ',
    'pvr': '\n                            26,21 €                        ',
  },
  {
    'nombre': 'Funda para Tablet con Organizador de Accesorios Flexi·Case InnovaGoods',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            5,99 €                        ',
    'pvr': '\n                            15,62 €                        ',
  },
  {
    'nombre': 'Espejo (110 x 3 x 75 cm) Madera de mindi',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            96,25 €                        ',
    'pvr': '\n                            105,87 €                        ',
  },
  {
    'nombre': 'Cuchara Medidora Quttin Plástico Eco (5 Pcs)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            0,56 €                        ',
    'pvr': '\n                            0,84 €                        ',
  },
  {
    'nombre': 'Paleta de Cocina Quttin Bambú (30 Cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            0,54 €                        ',
    'pvr': '\n                            0,83 €                        ',
  },
  {
    'nombre': 'Colador de Acero Inoxidable Exquisite Asas (28,5 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            2,37 €                        ',
    'pvr': '\n                            3,59 €                        ',
  },
  {
    'nombre': 'Horno Pirolítico Teka HLB8400P 70 L 3552W A+ Gris',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            340,54 €                        ',
    'pvr': '\n                            358,46 €                        ',
  },
  {
    'nombre': 'Caja de Almacenaje con Tapa Premier',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            2,91 €                        ',
    'pvr': '\n                            4,41 €                        ',
  },
  {
    'nombre': 'Cuchillo de Cocina Quttin (20 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            1,13 €                        ',
    'pvr': '\n                            1,71 €                        ',
  },
  {
    'nombre': 'Reloj Mujer Madison U4101-F2 (36 mm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            10,33 €                        ',
    'pvr': '\n                            11,74 €                        ',
  },
  {
    'nombre': 'Vitrina (190 x 90 x 40 cm) Madera de mindi',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            464,22 €                        ',
    'pvr': '\n                            510,64 €                        ',
  },
  {
    'nombre': 'Caja de Almacenaje con Tapa Combi Tontarelli 67 L Transparente (59 X 39 x 46 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            10,87 €                        ',
    'pvr': '\n                            16,49 €                        ',
  },
  {
    'nombre': 'Rodillo para Amasar Quttin (45,5 x 5 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            2,94 €                        ',
    'pvr': '\n                            4,45 €                        ',
  },
  {
    'nombre': 'Cubo para la Basura con Pedal Tontarelli Plástico Azul',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            4,49 €                        ',
    'pvr': '\n                            6,81 €                        ',
  },
  {
    'nombre': 'Caja de Almacenamiento Tontarelli 70 L Negro (79,2 x 39 x 35 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            19,91 €                        ',
    'pvr': '\n                            33,92 €                        ',
  },
  {
    'nombre': 'Aparato Anticelulítico Masajeador de Vacumterapia InnovaGoods',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            11,14 €                        ',
    'pvr': '\n                            28,02 €                        ',
  },
  {
    'nombre': 'Colgante Mujer Thomas Sabo 1328-060-17',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            12,50 €                        ',
    'pvr': '\n                            14,20 €                        ',
  },
  {
    'nombre': 'Cuenco Diamond (Ø 15 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            0,97 €                        ',
    'pvr': '\n                            1,36 €                        ',
  },
  {
    'nombre': 'Teclado con Touchpad CoolBox COO-TEW01-BK Negro',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            10,46 €                        ',
    'pvr': '\n                            12,02 €                        ',
  },
  {
    'nombre': 'Ratón Gaming con LED NGS GMX-115 1200 dpi Negro',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            6,04 €                        ',
    'pvr': '\n                            7,02 €                        ',
  },
  {
    'nombre': 'Stepper Cardio Twister InnovaGoods',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            56,99 €                        ',
    'pvr': '\n                            94,52 €                        ',
  },
  {
    'nombre': 'Reloj Mujer Jean Paul Gaultier 8502302 (37 mm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            84,00 €                        ',
    'pvr': '\n                            105,00 €                        ',
  },
  {
    'nombre': 'Set de 11 Fiambreras Privilege 500 ml',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            1,46 €                        ',
    'pvr': '\n                            2,21 €                        ',
  },
  {
    'nombre': 'Olla con Tapa de Cristal Quttin Acero inoxidable',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            8,67 €                        ',
    'pvr': '\n                            13,16 €                        ',
  },
  {
    'nombre': 'Plantillas Elevadoras de Silicona X5 cm InnovaGoods',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            1,88 €                        ',
    'pvr': '\n                            7,36 €                        ',
  },
  {
    'nombre': 'Caja de Almacenaje con Tapa Premier',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            6,11 €                        ',
    'pvr': '\n                            9,26 €                        ',
  },
  {
    'nombre': 'OUTLET Pedaleador Spin Trainer (Sin Embalaje)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            20,95 €                        ',
    'pvr': '\n                            46,71 €                        ',
  },
  {
    'nombre': 'Zapatero Confortime Tela (5 Estantes)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            9,24 €                        ',
    'pvr': '\n                            14,02 €                        ',
  },
  {
    'nombre': 'Fiambrera Hermética Doble con Cubiertos Bentower InnovaGoods',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            9,69 €                        ',
    'pvr': '\n                            20,58 €                        ',
  },
  {
    'nombre': 'Cuchillo Santoku Quttin (12 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            1,20 €                        ',
    'pvr': '\n                            1,81 €                        ',
  },
  {
    'nombre': 'Ensaladera Diamond (Ø 25 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            2,33 €                        ',
    'pvr': '\n                            3,28 €                        ',
  },
  {
    'nombre': 'Caja de Almacenaje con Tapa Tontarelli 80 L Transparente (59 X 39 x 48 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            11,49 €                        ',
    'pvr': '\n                            17,43 €                        ',
  },
  {
    'nombre': 'Reloj Mujer Radiant RA384205 (32 mm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            18,82 €                        ',
    'pvr': '\n                            20,91 €                        ',
  },
  {
    'nombre': 'Pastillas de Encendido Algon (32 Pcs)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            0,51 €                        ',
    'pvr': '\n                            0,79 €                        ',
  },
  {
    'nombre': 'Gafas de Sol Mujer Polaroid PLD-6021-S-4XQ (ø 58 mm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            26,03 €                        ',
    'pvr': '\n                            32,54 €                        ',
  },
  {
    'nombre': 'Soporte para Móviles IStuck Gadget and Gifts',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            0,40 €                        ',
    'pvr': '\n                            0,88 €                        ',
  },
  {
    'nombre': 'Altavoz Bluetooth Inteligente Asistente de Voz VASS InnovaGoods',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            14,53 €                        ',
    'pvr': '\n                            35,96 €                        ',
  },
  {
    'nombre': 'Afeitadora Recargable Ergonómica Multifunción 5 en 1 Shavestyler InnovaGoods',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            15,23 €                        ',
    'pvr': '\n                            24,71 €                        ',
  },
  {
    'nombre': 'Reloj Unisex Jean Paul Gaultier 8502801 (37 mm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            81,33 €                        ',
    'pvr': '\n                            101,66 €                        ',
  },
  {
    'nombre': 'Cuchillo Pelador de Verduras Quttin Misaki (13 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            1,41 €                        ',
    'pvr': '\n                            1,99 €                        ',
  },
  {
    'nombre': 'Cuchillo de Cocina Cuyfor (13,5 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            0,86 €                        ',
    'pvr': '\n                            1,31 €                        ',
  },
  {
    'nombre': 'Lápiz Masajeador Antiarrugas para Ojos y Labios InnovaGoods',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            5,99 €                        ',
    'pvr': '\n                            14,79 €                        ',
  },
  {
    'nombre': 'Lámpara Táctil Recargable de Silicona Ballena InnovaGoods',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            6,36 €                        ',
    'pvr': '\n                            15,63 €                        ',
  },
  {
    'nombre': 'Reloj Mujer Guess W0289L4 (39 mm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            97,50 €                        ',
    'pvr': '\n                            110,80 €                        ',
  },
  {
    'nombre': 'Sauna Facial Aprilla AFM-2808 40 ml 130W Blanco Morado',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            12,64 €                        ',
    'pvr': '\n                            17,83 €                        ',
  },
  {
    'nombre': 'Mini Humidificador Difusor de Aromas Black InnovaGoods',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            8,77 €                        ',
    'pvr': '\n                            20,58 €                        ',
  },
  {
    'nombre': 'Cuchillo para Pan Quttin (20 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            3,19 €                        ',
    'pvr': '\n                            4,83 €                        ',
  },
  {
    'nombre': 'Espátula para Plancha Quttin (8 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            0,99 €                        ',
    'pvr': '\n                            1,49 €                        ',
  },
  {
    'nombre': 'Mesa Plegable Auxiliar Multiuso InnovaGoods',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            9,23 €                        ',
    'pvr': '\n                            23,06 €                        ',
  },
  {
    'nombre': 'Especiero de Bambú Quttin (12 pcs) (19 x 19 x 23 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            12,49 €                        ',
    'pvr': '\n                            18,94 €                        ',
  },
  {
    'nombre': 'Espátula para Plancha Cuyfor Acero (21 Cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            0,84 €                        ',
    'pvr': '\n                            1,26 €                        ',
  },
  {
    'nombre': 'Cojín Damero Marrón',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            8,58 €                        ',
    'pvr': '\n                            9,44 €                        ',
  },
  {
    'nombre': 'Portátil Gaming MSI GL65-286XES 15,6" i7-9750H 16 GB RAM 512 GB SSD Negro',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            1.285,95 €                        ',
    'pvr': '\n                            1.339,53 €                        ',
  },
  {
    'nombre': 'Molde para Pizza Quttin (34 x 1 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            2,00 €                        ',
    'pvr': '\n                            3,02 €                        ',
  },
  {
    'nombre': 'Cargador Inalámbrico para Smartphones Qi Wh InnovaGoods',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            2,38 €                        ',
    'pvr': '\n                            6,53 €                        ',
  },
  {
    'nombre': 'Pelador Giratorio Quttin (17 x 7 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            0,99 €                        ',
    'pvr': '\n                            1,49 €                        ',
  },
  {
    'nombre': 'Mini Climatizador Evaporativo Portátil con LED Freezy Cube InnovaGoods',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            9,78 €                        ',
    'pvr': '\n                            24,71 €                        ',
  },
  {
    'nombre': 'Trolley para Portátil 2 Ruedas Subblim SUB-TRB-2WCT01 13,3"-17" Negro',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            42,69 €                        ',
    'pvr': '\n                            47,43 €                        ',
  },
  {
    'nombre': 'Paellera Algon Acero pulido Plateado',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            7,57 €                        ',
    'pvr': '\n                            11,49 €                        ',
  },
  {
    'nombre': 'Aspiradora con Bolsa BOSCH BGL4ZOOO 5 L 850W Rojo',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            115,10 €                        ',
    'pvr': '\n                            119,90 €                        ',
  },
  {
    'nombre': 'Reloj Mujer Kenneth Cole IKC4934 (36 mm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            42,05 €                        ',
    'pvr': '\n                            47,78 €                        ',
  },
  {
    'nombre': 'Jamonero de Madera Elegance Plus',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            7,99 €                        ',
    'pvr': '\n                            26,25 €                        ',
  },
  {
    'nombre': 'Lámpara Táctil Recargable de Silicona Panda InnovaGoods',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            7,69 €                        ',
    'pvr': '\n                            18,92 €                        ',
  },
  {
    'nombre': 'Cuchillo Pelador Quttin Sybarite Negro (9 Cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            1,33 €                        ',
    'pvr': '\n                            2,01 €                        ',
  },
  {
    'nombre': 'Prensa Ajos Quttin Plástico Eco (18 Cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            1,67 €                        ',
    'pvr': '\n                            2,54 €                        ',
  },
  {
    'nombre': 'Bandeja Privilege Acero inoxidable',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            2,31 €                        ',
    'pvr': '\n                            3,93 €                        ',
  },
  {
    'nombre': 'Llavero Morellato SD0315',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            9,06 €                        ',
    'pvr': '\n                            10,30 €                        ',
  },
  {
    'nombre': 'Power Bank con Altavoz CuboQ 3500 mAh',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            6,99 €                        ',
    'pvr': '\n                            13,97 €                        ',
  },
  {
    'nombre': 'Reloj Mujer Guess W0773L1 (44 mm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            80,00 €                        ',
    'pvr': '\n                            90,91 €                        ',
  },
  {
    'nombre': 'Cojín Bohemian Verde',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            9,82 €                        ',
    'pvr': '\n                            10,80 €                        ',
  },
  {
    'nombre': 'Cuchillo Pelador de Verduras Quttin Sybarite (15,5 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            2,79 €                        ',
    'pvr': '\n                            4,23 €                        ',
  },
  {
    'nombre': 'Mandolina-Rallador 5 en 1 Choppie+ InnovaGoods',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            5,24 €                        ',
    'pvr': '\n                            12,31 €                        ',
  },
  {
    'nombre': 'Macheta de Cocina Quttin (14 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            1,84 €                        ',
    'pvr': '\n                            2,80 €                        ',
  },
  {
    'nombre': 'Depiladora Facial Indolora con LED InnovaGoods',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            3,98 €                        ',
    'pvr': '\n                            9,83 €                        ',
  },
  {
    'nombre': 'Altavoz Inalámbrico con Soporte para Dispositivos Sonodock InnovaGoods',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            9,87 €                        ',
    'pvr': '\n                            20,58 €                        ',
  },
  {
    'nombre': 'Reloj Mujer K&Bros 9135-4-435 (34 mm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            26,67 €                        ',
    'pvr': '\n                            31,75 €                        ',
  },
  {
    'nombre': 'Escurridor para Fregadero Privilege Metal (45 X 35,4 x 12,5 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            4,91 €                        ',
    'pvr': '\n                            7,45 €                        ',
  },
  {
    'nombre': 'Cesta Multiusos Arianna Tontarelli Rectangular Negro',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            7,11 €                        ',
    'pvr': '\n                            10,80 €                        ',
  },
  {
    'nombre': 'Pendientes Mujer Elixa EL124-3744',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            11,67 €                        ',
    'pvr': '\n                            13,73 €                        ',
  },
  {
    'nombre': 'Cubo para la Basura Confortime 25 L',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            5,39 €                        ',
    'pvr': '\n                            8,16 €                        ',
  },
  {
    'nombre': 'Pulsera de Actividad Fitness InnovaGoods',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            7,96 €                        ',
    'pvr': '\n                            18,52 €                        ',
  },
  {
    'nombre': 'Medidor de Copas Quttin (15/30 ml)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            0,73 €                        ',
    'pvr': '\n                            1,11 €                        ',
  },
  {
    'nombre': 'Mesita de Noche (50 x 40 x 45 cm) Madera de mindi',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            96,25 €                        ',
    'pvr': '\n                            105,87 €                        ',
  },
  {
    'nombre': 'Toalla Deportiva de Enfriamiento Instantáneo Efecto Hielo InnovaGoods',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            2,48 €                        ',
    'pvr': '\n                            7,36 €                        ',
  },
  {
    'nombre': 'Cuchillo Santoku Quttin (16,5 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            1,26 €                        ',
    'pvr': '\n                            1,91 €                        ',
  },
  {
    'nombre': 'Taburete Confortime Blanco Gris',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            4,21 €                        ',
    'pvr': '\n                            5,94 €                        ',
  },
  {
    'nombre': 'Fiambrera Bormioli Rectangular (12,3 x 9,5 x 6,6 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            2,36 €                        ',
    'pvr': '\n                            3,32 €                        ',
  },
  {
    'nombre': 'Barbacoa de Carbón con Ruedas Algon Negro (ø 56 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            31,48 €                        ',
    'pvr': '\n                            53,65 €                        ',
  },
  {
    'nombre': 'Climatizador Evaporativo Portátil InnovaGoods 4,5 L 70W Gris',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            56,98 €                        ',
    'pvr': '\n                            70,99 €                        ',
  },
  {
    'nombre': 'Cuchillo para Chuletas Quttin Acero (11 Cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            1,29 €                        ',
    'pvr': '\n                            2,31 €                        ',
  },
  {
    'nombre': 'Anillo Hombre D&G DJ0736/21 (Talla 21)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            33,75 €                        ',
    'pvr': '\n                            38,35 €                        ',
  },
  {
    'nombre': 'Cuchillo para Chuletas Quttin Acero (11,5 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            1,03 €                        ',
    'pvr': '\n                            1,85 €                        ',
  },
  {
    'nombre': 'Pelador de Fruta y Verdura Quttin Negro (6 Cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            0,53 €                        ',
    'pvr': '\n                            0,80 €                        ',
  },
  {
    'nombre': 'Mini Humidificador Difusor de Aromas Honey Pine InnovaGoods',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            8,77 €                        ',
    'pvr': '\n                            20,58 €                        ',
  },
  {
    'nombre': 'Mesa Plegable (50 x 50 x 50 cm) Madera de teca',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            40,68 €                        ',
    'pvr': '\n                            44,75 €                        ',
  },
  {
    'nombre': 'Barbacoa de Carbón con Ruedas Algon Negro Rojo (52 X 27 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            25,75 €                        ',
    'pvr': '\n                            43,90 €                        ',
  },
  {
    'nombre': 'Mando a Distancia Universal NIMO MAN2057 Negro',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            3,05 €                        ',
    'pvr': '\n                            3,63 €                        ',
  },
  {
    'nombre': 'Plato Llano Santa Clara (Ø 19 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            0,73 €                        ',
    'pvr': '\n                            1,02 €                        ',
  },
  {
    'nombre': 'Selladora de Bolsas con Cúter e Imán InnovaGoods',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            4,54 €                        ',
    'pvr': '\n                            11,48 €                        ',
  },
  {
    'nombre': 'Recipientes de Cocina Ajustables y Herméticos InnovaGoods (Set de 3)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            8,70 €                        ',
    'pvr': '\n                            19,55 €                        ',
  },
  {
    'nombre': 'Saco de Boxeo de Pie Hinchable para Niños InnovaGoods',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            5,78 €                        ',
    'pvr': '\n                            14,79 €                        ',
  },
  {
    'nombre': 'Cesta Multiusos Arianna Tontarelli 25 L Cuadrada Blanco',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            5,93 €                        ',
    'pvr': '\n                            8,98 €                        ',
  },
  {
    'nombre': 'Mesa TV con Cajones (158 x 50 x 60 cm) Madera de mindi',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            323,45 €                        ',
    'pvr': '\n                            355,79 €                        ',
  },
  {
    'nombre': 'Bandeja Privilege Acero inoxidable',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            0,96 €                        ',
    'pvr': '\n                            1,45 €                        ',
  },
  {
    'nombre': 'Funda Sumergible para Móviles WpShield',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            0,90 €                        ',
    'pvr': '\n                            2,40 €                        ',
  },
  {
    'nombre': 'Pelador Giratorio Quttin',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            0,89 €                        ',
    'pvr': '\n                            1,35 €                        ',
  },
  {
    'nombre': 'Reloj Mujer K&Bros 9530-1-650 (34 mm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            45,33 €                        ',
    'pvr': '\n                            53,96 €                        ',
  },
  {
    'nombre': 'Barbacoa Portátil Algon Hierro Negro',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            9,50 €                        ',
    'pvr': '\n                            14,40 €                        ',
  },
  {
    'nombre': 'Plancha Grill 2 In 1 Algon Hierro fundido Negro',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            8,61 €                        ',
    'pvr': '\n                            13,06 €                        ',
  },
  {
    'nombre': 'Exprimidor-Regadera de Cítricos Manual Bitty InnovaGoods',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            2,68 €                        ',
    'pvr': '\n                            7,36 €                        ',
  },
  {
    'nombre': 'Cuchillo de Untar Cuyfor (6,5 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            0,46 €                        ',
    'pvr': '\n                            0,68 €                        ',
  },
  {
    'nombre': 'Grifo de Cerveza para Latas InnovaGoods',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            31,77 €                        ',
    'pvr': '\n                            57,77 €                        ',
  },
  {
    'nombre': 'eBook SPC 5610N 6" 4 GB SD Negro',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            52,52 €                        ',
    'pvr': '\n                            55,87 €                        ',
  },
  {
    'nombre': 'Centrifugadora para Ensalada Tontarelli 4,5 L Plástico (ø 24,5 x 16 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            4,09 €                        ',
    'pvr': '\n                            6,21 €                        ',
  },
  {
    'nombre': 'Robot Aspirador Inteligente Rovac 1000 InnovaGoods Blanco',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            11,15 €                        ',
    'pvr': '\n                            25,54 €                        ',
  },
  {
    'nombre': 'Colgador Confortime Blanco',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            0,77 €                        ',
    'pvr': '\n                            1,17 €                        ',
  },
  {
    'nombre': 'Reloj Mujer Pulsar PH8385X1 (36 mm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            34,06 €                        ',
    'pvr': '\n                            38,70 €                        ',
  },
  {
    'nombre': 'Embudo con Filtro Privilege Acero inoxidable',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            1,71 €                        ',
    'pvr': '\n                            2,60 €                        ',
  },
  {
    'nombre': 'Cacerola Con Tapa Percutti Acero inoxidable',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            18,82 €                        ',
    'pvr': '\n                            29,81 €                        ',
  },
  {
    'nombre': 'Organizador para Cubiertos Privilege Extensible (46 X 43 x 5 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            7,07 €                        ',
    'pvr': '\n                            10,72 €                        ',
  },
  {
    'nombre': 'Botella Deportiva con Filtro Infusor XL Infruitssion InnovaGoods',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            3,86 €                        ',
    'pvr': '\n                            9,89 €                        ',
  },
  {
    'nombre': 'Asadora Quttin (17,5 x 13 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            2,64 €                        ',
    'pvr': '\n                            3,73 €                        ',
  },
  {
    'nombre': 'Palo Selfie con Cable',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            0,99 €                        ',
    'pvr': '\n                            2,40 €                        ',
  },
  {
    'nombre': 'Cuchillo Jamonero Quttin (16 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            0,91 €                        ',
    'pvr': '\n                            1,39 €                        ',
  },
  {
    'nombre': 'Zapatero Confortime Madera (4 Estantes)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            7,51 €                        ',
    'pvr': '\n                            11,40 €                        ',
  },
  {
    'nombre': 'Cesto para la Ropa Flexi (42 x 41 x 50 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            5,33 €                        ',
    'pvr': '\n                            8,08 €                        ',
  },
  {
    'nombre': 'Mando a Distancia Universal NIMO MAN2055 Negro',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            3,75 €                        ',
    'pvr': '\n                            4,46 €                        ',
  },
  {
    'nombre': 'Colgador Confortime Extensible Acero (25 Cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            1,49 €                        ',
    'pvr': '\n                            2,26 €                        ',
  },
  {
    'nombre': 'Caja de Almacenaje con Tapa Tontarelli 54 L Transparente (59 X 39 x 33 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            8,84 €                        ',
    'pvr': '\n                            13,42 €                        ',
  },
  {
    'nombre': 'Auriculares con Micrófono Gaming CoolBox DG-AUR-02PRO Negro',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            17,04 €                        ',
    'pvr': '\n                            18,73 €                        ',
  },
  {
    'nombre': 'Cuchillo Mondador Quttin (6,5 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            1,33 €                        ',
    'pvr': '\n                            2,01 €                        ',
  },
  {
    'nombre': 'Chaleco Refrescante para Mascotas Medianas InnovaGoods - M',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            5,84 €                        ',
    'pvr': '\n                            11,15 €                        ',
  },
  {
    'nombre': 'Cenicero Confortime Acero',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            0,76 €                        ',
    'pvr': '\n                            1,15 €                        ',
  },
  {
    'nombre': 'Caja de Almacenaje con Tapa Tontarelli 29 L Transparente (47 X 36 x 24,5 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            5,77 €                        ',
    'pvr': '\n                            8,74 €                        ',
  },
  {
    'nombre': 'Dispensador de papel Confortime Pvc (34 X 20 x 9 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            6,16 €                        ',
    'pvr': '\n                            9,33 €                        ',
  },
  {
    'nombre': 'Reloj Hombre Ingersoll INJA001SLBK (40 mm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            57,33 €                        ',
    'pvr': '\n                            71,66 €                        ',
  },
  {
    'nombre': 'Parche Electroestimulador para Glúteos InnovaGoods',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            5,22 €                        ',
    'pvr': '\n                            13,27 €                        ',
  },
  {
    'nombre': 'Caja de Almacenaje con Tapa Premier Transparente',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            3,69 €                        ',
    'pvr': '\n                            7,65 €                        ',
  },
  {
    'nombre': 'Abrebotes Multifunción 5 en 1 InnovaGoods',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            2,37 €                        ',
    'pvr': '\n                            5,70 €                        ',
  },
  {
    'nombre': 'Emisor Térmico Digital Taurus CHTA-1500 1500W Blanco',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            70,05 €                        ',
    'pvr': '\n                            74,52 €                        ',
  },
  {
    'nombre': 'Smart TV LG 55UM7000 55" 4K Ultra HD D-LED WiFi Negro',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            364,26 €                        ',
    'pvr': '\n                            391,68 €                        ',
  },
  {
    'nombre': 'Lámpara Bombilla LED Táctil de Silicona con Altavoz Silitone InnovaGoods',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            15,34 €                        ',
    'pvr': '\n                            31,33 €                        ',
  },
  {
    'nombre': 'Colador para Servir Aperitivos Quttin (16 x 13 x 6 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            2,29 €                        ',
    'pvr': '\n                            3,46 €                        ',
  },
  {
    'nombre': 'Bols para Aperitivos 2 en 1 InnovaGoods (2 Piezas)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            3,58 €                        ',
    'pvr': '\n                            9,34 €                        ',
  },
  {
    'nombre': 'Organizador de Ducha con Ventosas Superadherentes InnovaGoods',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            8,54 €                        ',
    'pvr': '\n                            17,08 €                        ',
  },
  {
    'nombre': 'Escobilla para el Baño Tontarelli Plástico (13 X 13 x 40 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            5,23 €                        ',
    'pvr': '\n                            7,94 €                        ',
  },
  {
    'nombre': 'Maceta Resistente Marrón',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            0,37 €                        ',
    'pvr': '\n                            0,56 €                        ',
  },
  {
    'nombre': 'Reloj Mujer Michael Kors MK5606 (43 mm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            121,25 €                        ',
    'pvr': '\n                            137,78 €                        ',
  },
  {
    'nombre': 'Cuchillo para Pan Cuyfor (20,5 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            1,06 €                        ',
    'pvr': '\n                            1,61 €                        ',
  },
  {
    'nombre': 'Césped Artificial Little Garden (100 x 150 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            5,41 €                        ',
    'pvr': '\n                            8,20 €                        ',
  },
  {
    'nombre': 'Pulverizador de Aceite o Vinagre Quttin (4 x 17,7 x 4 cm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            3,79 €                        ',
    'pvr': '\n                            5,74 €                        ',
  },
  {
    'nombre': 'Clip LED para Gafas 360º InnovaGoods (Pack de 2)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            2,29 €                        ',
    'pvr': '\n                            5,70 €                        ',
  },
  {
    'nombre': 'Llavero Morellato SD7129',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            9,06 €                        ',
    'pvr': '\n                            10,30 €                        ',
  },
  {
    'nombre': 'Set de Cucharas Andrea Neutro (5 pcs)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            1,56 €                        ',
    'pvr': '\n                            2,36 €                        ',
  },
  {
    'nombre': 'Gafas de Sol Mujer Polaroid P8154-A (ø 62 mm)',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            21,59 €                        ',
    'pvr': '\n                            24,53 €                        ',
  },
  {
    'nombre': 'Memoria RAM Kingston HX426C16FB3/4 4 GB DDR4 PC4-21300',
    'imagen': 'https://www.bigbuy.net/public/img/Loading.gif',
    'pvd': '\n                            21,07 €                        ',
    'pvr': '\n                            23,41 €                        ',
  }];